config/routes.rb
Rails.application.routes.draw do
  get 'search' => 'pages#show'
  root 'pages#show'
  resources :searches
end

app/models/page.rb
class Page < ActiveRecord::Base

  def self.search(fname, lname)
    search = "#{fname} #{lname}"
    (!fname and !lname) ? [] : Page.where((['pages.tags LIKE ?'] * search.split.length).join(' OR '), *search.split(" ").map{|keyword| "%#{keyword} %"})
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def show
    # Rails.logger.debug params[:q].split(" ").join("% %")
    @pages = Page.search params[:fname], params[:lname]
    Rails.logger.debug @pages.inspect
    if @pages.empty?
      Search.create(fname: params[:fname], lname: params[:lname])
    end
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  
  def index
    @searches = Search.select('*, count(lname) as lcount, count(fname) as fcount').group(['fname', 'lname']).order('fcount desc, lcount desc').order('lcount desc')
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Fansearch</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pages/show.html.haml
= form_tag search_url, method: :get do
  = label_tag "Search"
  = text_field_tag :fname
  = text_field_tag :lname
  = submit_tag

%br
- unless params[:q].nil?
  Searched for: #{params[:q]}

%ul
  - @pages.each do |page|
    %li
      "#{page.url} - #{page.tags}"

app/views/searches/index.html.haml
%ul
  - @searches.each do |item|
    %li
      = "#{item.fname} #{item.lname}"